version: "3.9"
   
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - "./ipfs/staging:/export"
      - "./ipfs/data:/data/ipfs"
    environment:
      - HELLO="hello"
